
/**
 * This file is automatically generated by wheat-harvest.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.sample.glue.res.layout;

import android.support.v7.widget.RecyclerView;
import android.view.View;

public class MenuRow extends RecyclerView.ViewHolder {
    public MenuRow(View itemView) {
        super(itemView);
    }
}
