
/**
 * This file is automatically generated by wheat-harvest.
 * Do not modify this file -- YOUR CHANGES WILL BE ERASED!
 */

package x7c1.sample.glue.res.layout;

import android.view.View;
import android.widget.TextView;

public class MenuRowLabel extends MenuRow {

    public final TextView text;

    public MenuRowLabel(
        View itemView,
        TextView text
    ){
        super(itemView);
        this.text = text;
    }
}
